01-ast-detector by Denis Lochmelis
Static-Homeworks-CUB/fall2024 pull request #18
Opened 2024-09-28 15:21 UTC by DLochmelis33

Closes #11

2024-09-29 00:24 UTC, jubnzv requested changes
Please restore the example detector.

2024-09-29 01:29 UTC, jubnzv commented on assignments/1-ast-detectors/test/contract.tact
> +    // i only know how to write this single one based on https://docs.tact-lang.org/book/external#external-receivers
A few more possible examples: https://github.com/tact-lang/tact/blob/b38457330dd34190367a036983ca7ef225128ae3/src/test/contracts/case-receive.tact

2024-09-29 01:29 UTC, jubnzv commented on assignments/1-ast-detectors/test/contract.tact
> +    // i only know how to write this single one based on https://docs.tact-lang.org/book/external#external-receivers
A would also include a negative tests: just introduce an internal receiver to ensure the detector doesn't highlight it.

2024-10-02 18:11 UTC, DLochmelis33 commented on assignments/1-ast-detectors/test/contract.tact
> +    // i only know how to write this single one based on https://docs.tact-lang.org/book/external#external-receivers
:ok_hand:

2024-10-02 18:12 UTC, DLochmelis33 commented
Btw, the CI did not run for some reason

2024-10-03 04:02 UTC, jubnzv commented
> Btw, the CI did not run for some reason

It should not for the first-time contributors.

2024-10-03 04:11 UTC, jubnzv approved these changes
LGTM

2024-10-03 04:11 UTC, merged