Assignment 1: Unused Loop Variable - Mikhail Rodionychev
Static-Homeworks-CUB/fall2024 pull request #24
Opened 2024-10-06 21:26 UTC by Taifin

2024-10-06 23:22 UTC, jubnzv requested changes
`yarn fix-all` could help fixing the formatting.

2024-10-10 12:09 UTC, jubnzv requested changes
It works correctly. Let's adjust the implementation a bit before merging.

2024-10-10 12:09 UTC, jubnzv commented on assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts
> +        statement.kind == "statement_until"
nit: Why a different equals operation here?

2024-10-10 12:09 UTC, jubnzv commented on assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts
> +  ): number {
Why don't return a boolean here?

2024-10-14 17:09 UTC, Taifin commented on assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts
> +        statement.kind == "statement_until"
Fixed

2024-10-14 17:11 UTC, Taifin commented on assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts
> +  ): number {
`foldExpressions` for while visited the condition too and was finding extra usages of the variable, so I switched to counting instead of checking for presence. Fixed now anyway

2024-10-18 10:48 UTC, jubnzv commented on assignments/1-ast-detectors/unusedLoopVariable/unusedLoopVariable.ts
> +        statement.kind == "statement_until"
Well, actually we should prefer `==` in TypeScript to avoid surprises related to dynamic typing. But it will work here, so nevermind.

2024-10-18 10:50 UTC, jubnzv approved these changes

2024-10-18 10:50 UTC, merged