HW02 Kirill Shirokov
Static-Homeworks-CUB/fall2024 pull request #36
Opened 2024-10-23 11:20 UTC by shirokov-kirill

2024-10-25 06:00 UTC, jubnzv requested changes
The core logic looks good. Let's fix the scoping case and some minor issues before merging.

2024-11-16 22:15 UTC, shirokov-kirill commented on assignments/2-gen-kill-analyses/downwardExposedUses/downwardExposedUses.ts
> +//import { foldExpressions } from "@nowarp/misti/dist/src/internals/tactASTUtil";
Fixed

2024-11-16 22:15 UTC, shirokov-kirill commented on assignments/2-gen-kill-analyses/downwardExposedUses/downwardExposedUses.ts
> +  //BasicBlock,
Fixed

2024-11-16 22:15 UTC, shirokov-kirill commented on assignments/2-gen-kill-analyses/downwardExposedUses/downwardExposedUses.ts
> +  //  AstExpression,
Fixed

2024-11-16 22:16 UTC, shirokov-kirill commented on assignments/2-gen-kill-analyses/downwardExposedUses/downwardExposedUses.ts
> +//import { assert } from "console";
Fixed

2024-11-16 22:22 UTC, shirokov-kirill commented on assignments/2-gen-kill-analyses/downwardExposedUses/downwardExposedUses.ts
> +interface LiveVariableInfo {
Fixed

2024-11-16 22:25 UTC, shirokov-kirill commented on assignments/2-gen-kill-analyses/downwardExposedUses/downwardExposedUses.ts
> +  lastdef: VariableSet;
Fixed

2024-11-16 23:29 UTC, shirokov-kirill commented on assignments/2-gen-kill-analyses/downwardExposedUses/downwardExposedUses.spec.ts
> +// in = [a,1673,b,1664]
Is there a way to control such scope in misti? I only found an iteration through BasicBlocks (statements) with no `{` and `}` tokens, as it is a CFG, so I can't see the end of scope there.

2024-11-17 00:51 UTC, shirokov-kirill commented on assignments/2-gen-kill-analyses/downwardExposedUses/downwardExposedUses.ts
> +type VariableRecord = [string, BasicBlockIdx];
Fixed

2024-12-29 10:19 UTC, merged