HW02 by Denis Lochmelis
Static-Homeworks-CUB/fall2024 pull request #37
Opened 2024-10-24 20:06 UTC by DLochmelis33

closes #34

2024-10-25 06:27 UTC, jubnzv requested changes
It seems valid to me overall. Can we fix the scoping rules?

2024-10-25 06:27 UTC, jubnzv commented on assignments/2-gen-kill-analyses/copyPropagation/copyPropagation.ts
> + * An example detector that implements live variables analysis.
Let's remove irrelevant comments here and below.

2024-10-25 06:27 UTC, jubnzv commented on assignments/2-gen-kill-analyses/copyPropagation/copyPropagation.ts
> +      // i hate js i hate js i hate js i hate js i hate js i hate js i hate js i hate js i hate js i hate js i hate js i hate js
We are all on the same page. The analyzer will be implemented in OCaml, or in the worst case, in Rust, but we have to use TypeScript, since we have frontend and libraries written in it.

2024-10-25 06:27 UTC, jubnzv commented on assignments/2-gen-kill-analyses/copyPropagation/copyPropagation.ts
> +      // Optionally handle field assignments if needed
It's okay to skip this in the assignment.

2024-10-25 06:27 UTC, jubnzv commented on assignments/2-gen-kill-analyses/copyPropagation/copyPropagation.spec.ts
> +    // no cleanup of variables gone out of scope ==> b at the return point
Why do we keep variables gone out of scope? In the current implementation, it also won't work well with shadowing.

2024-10-25 14:01 UTC, InversionSpaces commented on assignments/2-gen-kill-analyses/copyPropagation/copyPropagation.ts
> +      // i hate js i hate js i hate js i hate js i hate js i hate js i hate js i hate js i hate js i hate js i hate js i hate js
skill issue ;)

2024-11-09 13:59 UTC, DLochmelis33 commented on assignments/2-gen-kill-analyses/copyPropagation/copyPropagation.spec.ts
> +    // no cleanup of variables gone out of scope ==> b at the return point
I don't know how to remove them :/ I suppose I could put them into the kill set, but I have no idea where I should get this info from

2024-12-29 10:20 UTC, merged